export const QUOTES = [
  "The only bad workout is the one that didn't happen.",
  "Push yourself because no one else is going to do it for you.",
  "Your body can stand almost anything. It's your mind you have to convince.",
  "The pain you feel today will be the strength you feel tomorrow.",
  "Don't stop when you're tired. Stop when you're done.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Do something today that your future self will thank you for.",
  "It never gets easier, you just get stronger.",
  "Train insane or remain the same.",
  "Sweat is just fat crying.",
  "You don't have to be great to start, but you have to start to be great.",
  "The hardest lift of all is lifting your butt off the couch.",
  "Fitness is not about being better than someone else. It's about being better than you used to be.",
  "Take care of your body. It's the only place you have to live.",
  "The difference between try and triumph is a little umph.",
  "Success starts with self-discipline.",
  "Your health is an investment, not an expense.",
  "Strive for progress, not perfection.",
  "A one-hour workout is 4% of your day. No excuses.",
  "The body achieves what the mind believes.",
  "Strength does not come from the body. It comes from the will of the soul.",
  "You are one workout away from a good mood.",
  "Believe in yourself and all that you are.",
  "Champions aren't made in gyms. Champions are made from something deep inside.",
  "The secret of getting ahead is getting started.",
  "Fall in love with taking care of yourself.",
  "Your only limit is you.",
  "Be stronger than your excuses.",
  "Discipline is doing what needs to be done even when you don't want to.",
  "Every rep counts. Every set matters.",
  "Results happen over time, not overnight. Work hard, stay consistent.",
  "The gym is my therapy.",
  "Sore today, strong tomorrow.",
  "You didn't come this far to only come this far.",
  "Make yourself proud.",
  "Hustle for that muscle.",
  "Eat clean. Train dirty.",
  "No pain, no gain.",
  "Be the best version of yourself.",
  "Your future self is watching you right now through memories.",
  "Motivation gets you started. Habit keeps you going.",
  "The only way to define your limits is by going beyond them.",
  "Don't wish for it. Work for it.",
  "Excuses don't burn calories.",
  "You are what you repeatedly do.",
  "Consistency is what transforms average into excellence.",
  "One day or day one. You decide.",
  "The clock is ticking. Are you becoming the person you want to be?",
  "Small steps every day lead to big results.",
  "Your health is your wealth.",
  "Fitness is a journey, not a destination.",
  "Strong is the new beautiful.",
  "Work hard in silence. Let success make the noise.",
  "The only person you should try to be better than is who you were yesterday.",
  "Energy and persistence conquer all things.",
  "You have to expect things of yourself before you can do them.",
  "It's not about having time. It's about making time.",
  "The harder you work, the luckier you get.",
  "Believe you can and you're halfway there.",
  "Success is the sum of small efforts repeated day in and day out.",
  "Don't limit your challenges. Challenge your limits.",
  "Great things never come from comfort zones.",
  "You are stronger than you think.",
  "Every workout is progress.",
  "Train like a beast. Look like a beauty.",
  "Dedication sees dreams come true.",
  "The best project you'll ever work on is you.",
  "Fitness is not a destination. It is a way of life.",
  "Rise and grind.",
  "Your body is a reflection of your lifestyle.",
  "Be patient. Good things take time.",
  "Earn your body.",
  "Sweat now. Shine later.",
  "You've got what it takes.",
  "Keep going. You're doing great.",
  "Today's pain is tomorrow's power.",
  "Make it happen. Shock everyone.",
  "The gym doesn't care about your feelings. Show up anyway.",
  "Strength is built in the moments you want to quit.",
  "You are capable of more than you know.",
  "Progress, not perfection.",
  "Every day is a new opportunity to improve yourself.",
  "The only way out is through.",
  "Commit to be fit.",
  "Your health is your most valuable asset.",
  "Don't count the days. Make the days count.",
  "Hard work beats talent when talent doesn't work hard.",
  "You're not just building a body. You're building a mindset.",
  "Show up. Work hard. Be consistent.",
  "The grind never stops.",
  "Fuel your body. Feed your soul.",
  "Champions train. Losers complain.",
  "Be the energy you want to attract.",
  "Fitness is the best investment you can make.",
  "Your body hears everything your mind says.",
  "Stay focused and never give up.",
  "The pain is temporary. The results are permanent.",
  "You are your only competition.",
  "Dream it. Believe it. Achieve it.",
  "Start where you are. Use what you have. Do what you can.",
];
